# Generated by Django 5.2.1 on 2025-06-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evaluacion_pregunta_respuesta_resultadoevaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='seccion',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
