# Generated by Django 5.2.1 on 2025-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_seccion_options_seccion_orden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultadoevaluacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='respuestas_usuario',
            field=models.ManyToManyField(blank=True, to='core.respuesta'),
        ),
        migrations.AlterField(
            model_name='resultadoevaluacion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultadoevaluacion',
            name='puntaje_obtenido',
            field=models.IntegerField(),
        ),
    ]
